name: gophermart-atlas

services:
  pgsql:
    image: postgres:16
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  atlas:
    depends_on:
      pgsql:
        condition: service_healthy
    build:
      context: .
      dockerfile: .docker/atlas/Dockerfile
    restart: no
    volumes:
      - "./migrations:/migrations/migrations"
